[tool.commitizen]
name = "cz_conventional_commits"
version = "0.4.1"
tag_format = "$version"

[tool.black]
line-length = 79
skip-string-normalization = true

[tool.isort]
profile="black"
multi_line_output=3
known_third_party=["sqlalchemy"]
known_tests=["tests"]
sections=["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER","TESTS"]
import_heading_stdlib="Standard Library"
import_heading_thirdparty="Third Party Library"
import_heading_firstparty="Local Module"
import_heading_tests="Tests Module"
include_trailing_comma="True"
line_length=79